### ISSUE TITLE
Tabs can only be closed in order of opening

### ISSUE THREAD

**Issue by Fiona-J-W** [CVVisualPSETeam/CVVisual#4]
If you open two calls $1 and $2 in new tabs and close $1, it is impossible to close $2.

**Comment by parttimenerd** [comment]
Hmmm...
The bug is obvious (to me):
I have a map mapping a tab index (tab position) to a CallTab in the CallWindow class, but this map only gets updated by adding a new tab. I forgot to update it more often.
But a better idea: Why not just adding the CallTab id to the tab description (e.g. `[100] awesome call`, shown in the tab header)? It's kind of a dirty hack, but would simply things - any opinion on that?

**Comment by Fiona-J-W** [comment]
No parsing of titles to get information about the titled stuff (in this case the tabs)!

I would propose to use a std::vector instead of the map and remove by removing from the middle of the vector than. In most cases this should be a trivial change that might end up being simpler than the current map. It would also be faster.

**Comment by parttimenerd** [comment]
I would propose to myself to RTFM...

An std::vector would be only a minor improvement. I won't depend on the index in the tab bar (or the displayed header) at all...

**Comment by parttimenerd** [comment]
The tab bar lets you set a QVariant data item for each tab index: The CallWindow is now able to get the CallTab of each tab directly.
